### ISSUE TITLE
Problem during installing mdbook-admonish

### ISSUE THREAD

**Issue by Ciamma** [tommilligan/mdbook-admonish#11]
Good morning, I was installing mdbook-admonish but the following problem appeared:
![mdbook-admonish_error](https://user-images.githubusercontent.com/30376334/155840990-5dfd9d3e-f5df-447f-95f9-4345242a6ced.png)

**Comment by tommilligan** [comment]
Hey, thanks for checking out the project!

`mdbook-admonish` currently has an MSRV of 1.58.0 - the error you posted is due to you using an older rust version.

What version of rust are you using? If it's not too far behind and it's not possible for you to upgrade, let me know and I'll see what changes I would need to make to support it.

You can find the currently supported MSRV at any time [in the changelog](https://github.com/tommilligan/mdbook-admonish/blob/main/CHANGELOG.md), or by seeing what is tested in CI.

**Comment by Ciamma** [comment]
Thanks, I've just updated rust version and it worked
