### ISSUE TITLE
Using mdbook-admonish changes the style of the `<details>` tag

### ISSUE THREAD

**Issue by gonzaponte** [tommilligan/mdbook-admonish#117]
After installing the package in the book, the style of the `<summary>` tag changed completely.

There are a number of `:is` calls in `mdbook-admonish.css` like `:is(.admonition-title, summary) ` with the consequence that it changes the style of all summaries, not just those created by admonitions.

Can this be fixed?

**Comment by tommilligan** [comment]
I think should already be fixed in https://github.com/tommilligan/mdbook-admonish/pull/112

You should try updating to the latest version, and installing the latest CSS assets:

```bash
# Install latest version
cargo install mdbook-admonish
# Update bundled CSS assets
mdbook-admonish install .
```

If that doesn't solve this for you, could you provide some more information about your version of `mdbook` and `mdbook-admonish`, and which css rule you are seeing affecting your elements?

**Comment by gonzaponte** [comment]
Apologies for the late reply. We are using this package through `nix`, which doesn't have the latest version. We *will try* to update the `nix` package to the latest version and see if this fixes the issue, but we have some other higher-priority issues on our hands.  Thank you for your prompt reply!

**Comment by tommilligan** [comment]
Closing as stale, please open a new issue if still relevant.
