### ISSUE TITLE
Any way to specify inline?

### ISSUE THREAD

**Issue by schungx** [tommilligan/mdbook-admonish#2]
Floating an block inline to the right or left is very useful and can be done via the `inline` style.

Can we add this?

**Comment by tommilligan** [comment]
My inclination is **no**, though I'm open to being persuaded otherwise.

As currently implemented, I think this plugin has the nice property of replacing a code **block** with another (nicer styled) **block**.  Both of these blocks have the same layout, which preserves the flow of the page, how it interacts with other elements and so on. This makes the plugin purely about **presentation**, and not about layout.

![image](https://user-images.githubusercontent.com/12255914/154864032-e1625143-e7ba-41df-891d-f694f902f21a.png)

![image](https://user-images.githubusercontent.com/12255914/154864050-6f440eb2-369f-441f-8579-ef6c2842f53a.png)

_How_ the blocks are laid out feels like a fairly orthogonal concern. I could imagine a separate plugin, `mdbook-float`, that is responsible for wrapping blocks of content and floating them left or right on the page - and you could nest an admonishment inside it, if you so wished, but also images, links, notes, etc.

It's also easily achievable with a simple HTML wrapper:in your own book:

![image](https://user-images.githubusercontent.com/12255914/154864422-5c14e1c5-56fa-45c4-9b00-4b00a2ec8659.png)

Source markdown:

~~~markdown
## References and Borrowing

<div style="float:left;margin-right:2rem;margin-bottom:2rem;width:330px">

```admonish tip "_Referencing_ and <i>dereferencing</i>"
The opposite of *referencing* by using `&` is *dereferencing*, which is
accomplished with the <span style="color: hotpink">dereference operator</span>, `*`.
```

</div>

The issue with the tuple code in Listing 4-5 is that we have to return the
`String` to the calling function so we can still use the `String` after the
call to `calculate_length`, because the `String` was moved into
`calculate_length`. Instead, we can provide a reference to the `String` value.
A _reference_ is like a pointer in that it’s an address we can follow to access
data stored at that address that is owned by some other variable. Unlike a
pointer, a reference is guaranteed to point to a valid value of a particular
type. Here is how you would define and use a `calculate_length` function that
has a reference to an object as a parameter instead of taking ownership of the
value:
~~~
