### ISSUE TITLE
Admonition title bar too large in 1.6.0

### ISSUE THREAD

**Issue by gggto** [tommilligan/mdbook-admonish#23]
Since the 1.6.0 update, admonition titles appear too large. I did update the CSS by running `mdbook-admonition install` again. Maybe this is related to the `<a>` fields that release added in the generation?

![Screenshot 2022-04-29 at 17-29-31 Introduction - QEM Pratical Advanced Script Programming for Image Processing in Digital Micrograph](https://user-images.githubusercontent.com/47183108/165976181-31b67c64-9515-4da9-a569-1b086c33a553.png)

**Comment by tommilligan** [comment]
Thanks for reporting this - are you sure that the new CSS has file has replaced your existing installation?

I ask because this is exactly what I would expect to see with the CSS from 1.5.0 still installed. If you're sure, could you post the following for me to debug further:

- `book.toml` mdbook-admonish preprocessor section
- The HTML of the rendered admonishment, such as:
```html
<div id="admonition-info" class="admonition info">
<div class="admonition-title">
<a class="admonition-anchor-link" href="#admonition-info">
<p>Info</p>
</a>
</div>
<div>
<p>A beautifully styled message.</p>
</div>
</div>
```
- The CSS as loaded into your browser in the `mdbook-admonish.css` file. You can find it in your browser devtools under the `Sources` section:
![image](https://user-images.githubusercontent.com/12255914/165984282-abaf2492-bef6-4a44-9a47-184c78dabb1c.png)

I've highlighted the newly added CSS rule I would expect to suppress this problem, which was added here: https://github.com/tommilligan/mdbook-admonish/commit/0e235cb9b52d96476bd4bb6e23959ec1919a9b57#diff-132650f29be6ca05d18cfb5bfbf0262fdd034b0358764d0dcaf36f1763419b95R146

---

If you're working on an open source repo, also happy for a link to a branch or similar so I can take a look.

**Comment by gggto** [comment]
Ok, so I don't really get what is going on; today before I could try any of that suggestion, the issue was gone. Everything looks normal now, but I haven't changed the CSS or anything since that last screenshot (and before taking that screenshot, I try deleting my `book` directory, deleting the `mdbook-admonish.css` before `mdbook-admonish install`, running `mdbook serve --open` again to allow rebuilding everything from scratch and opening the webpage on a fresh tab…).

I guess, maybe I got bitten by Firefox's cache?

Anyway, sorry for the noise, and thanks a lot for your help!

**Comment by tommilligan** [comment]
No worries at all, glad it works now!
